### ISSUE TITLE
FMX.Media.pas.rej

### ISSUE THREAD

**Issue by Rollo62b** [DelphiWorlds/DelphiPatches#1]
Hi Dave,

I was just checking the patches, with D11 +November patch and Codex 1.5.1.
It seems to have issues with FMX.MediaLibrary.iOS.RSP-20875.11.0.patch,
which strangely seems to copy and refer to FMX.Media.pas for no reason, not using the FMX.MediaLibrary.iOS.pas.
It copies and creates FMX.Media.pas, FMX.Media.pas.orig, FMX.Media.pas.rej, what I have checked in various locations. 

My IDE installation is located in D:\Prg\Embarcadero, not in the normal C:\Program folder, maybe that is the reason ?

I cannot see any issues in the patch file itself, not sure if this could be a problem in Codex or the patcher itself,
only the wrong source folder:
diff --git "a/C:\\Program Files (x86)\\Embarcadero\\Studio\\22.0\\source\\fmx\\FMX.MediaLibrary.iOS.pas" "b/Z:\\Patches\\Delphi\\11\\FMX.MediaLibrary.iOS.pas"

Other patches have the same, but they do work fine, like:
diff --git "a/C:\\Program Files (x86)\\Embarcadero\\Studio\\22.0\\source\\fmx\\FMX.Canvas.D2D.pas" "b/Z:\\Patches\\Delphi\\11\\FMX.Canvas.D2D.pas"

In FMX.Media.pas.rej:
--- /dev/null
+++ FMX.MediaLibrary.iOS.pas
@@ -21,6 +21,8 @@ uses
   System.SysUtils, System.Classes, System.Types, System.Math, System.Generics.Collections,
   FMX.MediaLibrary, FMX.Types, FMX.Types3D, FMX.Controls,
   FMX.Platform, FMX.Graphics, FMX.Helpers.iOS, iOSapi.MediaPlayer, iOSapi.Foundation, iOSapi.UIKit, iOSapi.CoreGraphics,
+  // PATCH https://quality.embarcadero.com/browse/RSP-20875
+  iOSapi.CocoaTypes,
   Macapi.ObjectiveC, Macapi.Helpers, iOSapi.AssetsLibrary, System.TypInfo, Macapi.ObjCRuntime, FMX.Consts;
 
 type
@@ -67,6 +69,8 @@ type
   TImageDelegate = class(TOCLocal, UIImagePickerControllerDelegate)
   private
     [Weak] FImageManager: TImageManagerCocoa;
+    // PATCH https://quality.embarcadero.com/browse/RSP-20875
+    FIsFullScreen: Boolean;
     FParams: TParamsPhotoQuery;
   protected
     procedure DoDidFinishTaking(const AImage: TBitmap);
@@ -75,6 +79,8 @@ type
     function GetAngleOfImageOrientation(const AImage: UIImage): Single;
   public
     constructor Create(const AImageManager: TImageManagerCocoa);
+    // PATCH https://quality.embarcadero.com/browse/RSP-20875
+    property IsFullScreen: Boolean read FIsFullScreen write FIsFullScreen;
     property Params: TParamsPhotoQuery read FParams write FParams;
     { UIImagePickerControllerDelegate }
     procedure imagePickerController(picker: UIImagePickerController; didFinishPickingImage: UIImage; editingInfo: NSDictionary); overload; cdecl;
@@ -95,6 +101,40 @@ type
     procedure Share(const AControl: TControl; const AText: string; const ABitmap: TBitmap);
   end;
 
+// PATCH https://quality.embarcadero.com/browse/RSP-20875 start
+  IImagePickerController = interface(UIImagePickerController)
+    ['{B9BB3FA5-9C0D-4BFA-A905-6575B09A972E}']
+  end;
+
+  TImagePickerController = class(TOCLocal)
+  protected
+    function GetObjectiveCClass: PTypeInfo; override;
+  public
+    constructor Create;
+    function supportedInterfaceOrientations: NSUInteger; cdecl;
+  end;
+
+constructor TImagePickerController.Create;
+var
+  V: Pointer;
+begin
+  inherited;
+  V := UIImagePickerController(Super).init;
+  if GetObjectID <> V then
+    UpdateObjectID(V);
+end;
+
+function TImagePickerController.GetObjectiveCClass: PTypeInfo;
+begin
+  Result := TypeInfo(IImagePickerController);
+end;
+
+function TImagePickerController.supportedInterfaceOrientations: NSUInteger;
+begin
+  Result := SharedApplication.keyWindow.rootViewController.supportedInterfaceOrientations;
+end;
+// PATCH https://quality.embarcadero.com/browse/RSP-20875 end
+
 procedure RegisterMediaLibraryServices;
 var
   ImageManager: TImageManagerCocoa;
@@ -229,10 +269,15 @@ procedure TImageManagerCocoa.TakeImage(const AControl: TControl; const ASourceTy
   procedure ShowPicker;
   begin
     // Camera for iPad is showed only in full screen on iPad and iPhone
-    if not IsPad or (ASourceType = UIImagePickerControllerSourceTypeCamera) then
+    // PATCH https://quality.embarcadero.com/browse/RSP-20875 start
+    // If you want the picker to be full screen *always*, modify the next line to: FImageDelegate.IsFullScreen := True;
+    FImageDelegate.IsFullScreen := not IsPad or (ASourceType = UIImagePickerControllerSourceTypeCamera);
+    // if not IsPad or (ASourceType = UIImagePickerControllerSourceTypeCamera) then
+    if FImageDelegate.IsFullScreen then
       ShowInFullScreen
     else
       ShowInPopover;
+    // PATCH https://quality.embarcadero.com/browse/RSP-20875 end
   end;
 
 begin
@@ -243,7 +288,11 @@ begin
       FImagePicker.setDelegate(nil);
       FImagePicker.release;
     end;
-    FImagePicker := TUIImagePickerController.Create;
+
+    // PATCH https://quality.embarcadero.com/browse/RSP-20875 start
+    // FImagePicker := TUIImagePickerController.Create;
+    FImagePicker := UIImagePickerController(TImagePickerController.Create.Super);
+    // PATCH https://quality.embarcadero.com/browse/RSP-20875 end
     FImagePicker.retain;
     FImagePicker.setDelegate(FImageDelegate.GetObjectID);
 
@@ -311,10 +360,13 @@ end;
 
 procedure TImageDelegate.HidePicker(const APicker: UIImagePickerController);
 begin
-  if (FImageManager <> nil) and IsPad and (APicker.sourceType <> UIImagePickerControllerSourceTypeCamera) then
+  // PATCH https://quality.embarcadero.com/browse/RSP-20875 start
+  // if (FImageManager <> nil) and IsPad and (APicker.sourceType <> UIImagePickerControllerSourceTypeCamera) then
+  if (FImageManager <> nil) and not FIsFullScreen then
     FImageManager.ClosePopover
   else
     APicker.dismissModalViewControllerAnimated(True);
+  // PATCH https://quality.embarcadero.com/browse/RSP-20875 end
 end;
 
 procedure TImageDelegate.imagePickerController(picker: UIImagePickerController; didFinishPickingImage: UIImage;

**Comment by DelphiWorlds** [comment]
Do you have more than one version of Delphi installed on the same machine? I think that may be the issue

**Comment by DelphiWorlds** [comment]
Actually, scratch that.. something is wrong with the patch logic. I'm looking into it

**Comment by DelphiWorlds** [comment]
As per my last comment, the bug is actually in Codex. I've put an "emergency" update to Codex, [here](http://pusherizor.com/Downloads/CodexSetup_1.5.2_Beta.exe)

**Comment by Rollo62b** [comment]
I have only D11 installed and usually clean complete before I upgrade new version.
All the other files patches well, it's only the MediaLibrary that fails.

Thanks for the fast update, I will check it.

**Comment by Rollo62b** [comment]
Would like to, but the link "pusherizor.com/Downloads/CodexSetup_1.5.2_Beta.exe" fails to download, I see only infinite ani icon.
Cannot reach "pusherizor.com" either, maybe thats all part of the log4J issue, on all servers :-)

**Comment by DelphiWorlds** [comment]
Try [here](https://github.com/DelphiWorlds/MiscStuff/blob/master/CodexSetup_1.5.2_Beta.exe) instead

**Comment by Rollo62b** [comment]
Its working now with FMX.MediaLibrary too, thanks.
What I've noticed is that it doesn't produce the backup .orig file any longer, alongside with the patched file,
but that is fine for me.

I will look into this patch next week or later more deeply.
